import type { Metadata } from 'next';
import Link from 'next/link';
import HeaderEn from '@/components/layout/HeaderEn';
import Footer from '@/components/layout/Footer';

export const metadata: Metadata = {
  title: 'General Contractor Website Design That Generates Leads | Pixeloria',
  description:
    'Professional websites for general contractors, built to present the full range of your project types, showcase a strong project gallery and win larger jobs. Mobile-first website design for US general contractors.',
  alternates: {
    canonical: 'https://pixeloria.fr/en/general-contractor-websites',
  },
  openGraph: {
    type: 'website',
    url: 'https://pixeloria.fr/en/general-contractor-websites',
    title: 'General Contractor Website Design That Generates Leads | Pixeloria',
    description:
      'Professional websites for general contractors, built to present the full range of your project types, showcase a strong project gallery and win larger jobs. Mobile-first website design for US general contractors.',
    locale: 'en_US',
    siteName: 'Pixeloria',
  },
};

const includeItems = [
  {
    label: 'Services and project types overview',
    desc: 'A clear breakdown of the project types you handle — additions, renovations, ground-up builds — so visitors immediately understand your scope of work.',
  },
  {
    label: 'Project gallery',
    desc: 'A strong, well-organized gallery of completed projects across different trades and project sizes, not just one type of job.',
  },
  {
    label: 'Licensing and insurance details',
    desc: 'Clear, generic presentation of your license and insurance status, where applicable — the kind of information larger-project clients check before reaching out.',
  },
  {
    label: 'Service area page',
    desc: 'A clear list of the towns, counties or regions your company serves.',
  },
  {
    label: 'Estimate request form',
    desc: 'A straightforward form so homeowners and property managers can request a project estimate without picking up the phone.',
  },
  {
    label: 'Mobile call button',
    desc: 'A tap-to-call button, always visible, for visitors researching contractors on their phone.',
  },
];

const scopeFeatures = [
  {
    title: 'Full project scope, not one trade',
    desc: 'Unlike a single-trade specialist website, a general contractor site needs to communicate a broader scope of work — additions, whole-home renovations, ground-up builds and subcontractor coordination — without overwhelming the visitor.',
  },
  {
    title: 'Project-management credibility',
    desc: 'Larger projects mean higher stakes for the client. The site is structured to convey organization and project-management competence, not just a list of services.',
  },
  {
    title: 'Built for a longer research process',
    desc: 'Homeowners planning a major renovation and property managers evaluating contractors for commercial work tend to research extensively and compare several companies before reaching out.',
  },
  {
    title: 'Residential and commercial paths',
    desc: 'Separate, clearly labeled paths for residential clients and commercial or property-management clients, since their priorities and project types differ.',
  },
];

const galleryFeatures = [
  {
    title: 'Before/after and completed-projects gallery',
    desc: 'A prominent gallery showing the range of past work — different project types and sizes — is one of the most important trust signals on a general contractor website.',
  },
  {
    title: 'Organized by project type',
    desc: 'Projects grouped by category (additions, renovations, new builds, commercial work) so visitors can quickly find examples relevant to what they are planning.',
  },
  {
    title: 'Clear estimate path from every project',
    desc: 'Each project example links back to a simple way to request an estimate, so interest generated by the gallery converts into an inquiry.',
  },
];

const localSeoItems = [
  { label: 'Service area pages', desc: 'Individual pages for each town, county or region your company serves.' },
  { label: 'Google Business Profile alignment', desc: 'Business name, address and services kept consistent with your website.' },
  { label: 'Structured data for services', desc: 'Structured data that describes your services and service area to search engines.' },
  { label: 'Licensing details displayed clearly', desc: 'License and insurance information displayed where visitors expect it.' },
];

const faqs = [
  {
    q: 'How much does a general contractor website cost?',
    a: 'Pixeloria general contractor websites start at $499 for a one-page website. Multi-page websites with individual project-type pages and a full project gallery start at $899.',
  },
  {
    q: 'How long does it take to build a general contractor website?',
    a: 'A one-page website can generally be delivered within five business days after we receive all required content. Larger multi-page websites with a full project gallery may take one to three weeks.',
  },
  {
    q: 'Can you redesign my existing general contracting website?',
    a: 'Yes. Pixeloria can redesign outdated general contractor websites while improving the project gallery, mobile usability and local search structure.',
  },
  {
    q: 'Can my website show both residential and commercial projects?',
    a: 'Yes. We commonly structure general contractor websites with separate, clearly labeled sections for residential and commercial or property-management work.',
  },
  {
    q: 'Do you guarantee first-page Google rankings?',
    a: 'No legitimate agency can guarantee a specific Google ranking. We focus on building a technically strong, well-structured website that supports your visibility over time.',
  },
];

export default function GeneralContractorWebsitesPage() {
  const serviceSchema = {
    '@context': 'https://schema.org',
    '@type': 'Service',
    name: 'General contractor website design',
    provider: {
      '@type': 'Organization',
      name: 'Pixeloria',
      url: 'https://pixeloria.fr',
    },
    description: 'Website design services for residential and commercial general contractors.',
    areaServed: { '@type': 'Country', name: 'United States' },
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((item) => ({
      '@type': 'Question',
      name: item.q,
      acceptedAnswer: { '@type': 'Answer', text: item.a },
    })),
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <HeaderEn />
      <main>

        {/* Hero */}
        <section className="page-hero section">
          <div className="container">
            <div className="page-hero-inner">
              <nav className="breadcrumb" aria-label="Breadcrumb">
                <Link href="/en">Home</Link>
                <span aria-hidden="true"> › </span>
                <span>General Contractor Websites</span>
              </nav>
              <span className="eyebrow">General contractors</span>
              <h1>General Contractor Website Design That Generates Leads</h1>
              <p className="page-hero-sub">
                Pixeloria builds websites for general contractors across the United States —
                companies that oversee full projects and often coordinate subcontractors across
                additions, renovations and ground-up builds. Every website is structured to
                present the range of your work, showcase a strong project gallery and build the
                credibility larger projects require.
              </p>
              <div className="page-hero-actions">
                <Link href="/en/free-website-audit" className="btn btn-primary">
                  Get a Free Website Audit
                  <svg className="btn-icon" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                    <path d="M4 10h12M11 5l5 5-5 5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </Link>
                <Link href="/en/offers" className="btn btn-secondary">See Pricing</Link>
              </div>
            </div>
          </div>
        </section>

        {/* Quick Answer */}
        <section className="section">
          <div className="container">
            <div className="include-item" style={{ maxWidth: '760px' }}>
              <strong>Quick answer</strong>
              <p>
                A general contractor website should clearly present the full range of project
                types you handle, since general contractors typically oversee broader-scope work
                than a single-trade specialist. Because average project value and complexity are
                higher, the site should lead with a strong project gallery, communicate
                project-management credibility, list licensing and insurance information where
                applicable, and give homeowners and property managers a simple way to request a
                project estimate.
              </p>
            </div>
          </div>
        </section>

        {/* Website Design for General Contractors */}
        <section className="section section-tinted">
          <div className="container">
            <div className="section-heading">
              <span className="eyebrow">Built for general contractors</span>
              <h2>Website Design for General Contractors</h2>
              <p className="section-sub">
                Pixeloria builds websites for companies that provide general contracting
                services — Pixeloria itself does not perform construction work. Our job is to
                design and build the website your company uses to win larger, more complex
                projects.
              </p>
            </div>
            <div className="benefits-grid">
              <div className="benefit-card">
                <span className="benefit-num">01</span>
                <h3>Broader scope, clearly presented</h3>
                <p>Your website needs to communicate the full breadth of what you handle — not a single trade — without becoming confusing to navigate.</p>
              </div>
              <div className="benefit-card">
                <span className="benefit-num">02</span>
                <h3>Gallery-first credibility</h3>
                <p>A strong completed-projects gallery is often the deciding factor for a homeowner or property manager comparing several contractors.</p>
              </div>
              <div className="benefit-card">
                <span className="benefit-num">03</span>
                <h3>Built to convert bigger decisions</h3>
                <p>Larger projects mean longer research and more comparison. Every page is designed to build trust and move a serious inquiry toward an estimate request.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Why General Contractor Websites Are Different */}
        <section className="section">
          <div className="container">
            <div className="section-heading">
              <span className="eyebrow">What makes it different</span>
              <h2>Why General Contractor Websites Are Different</h2>
              <p className="section-sub">
                General contractors compete on scope, project management and trust — not on a
                single service. Your website needs to reflect that.
              </p>
            </div>
            <div className="benefits-grid">
              {scopeFeatures.map((f, i) => (
                <div key={f.title} className="benefit-card">
                  <span className="benefit-num">0{i + 1}</span>
                  <h3>{f.title}</h3>
                  <p>{f.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* What Every General Contractor Website Should Include */}
        <section className="section section-tinted">
          <div className="container">
            <div className="section-heading">
              <span className="eyebrow">The essentials</span>
              <h2>What Every General Contractor Website Should Include</h2>
              <p className="section-sub">
                These are the elements homeowners and property managers look for before they
                decide to request an estimate from a general contractor.
              </p>
            </div>
            <div className="includes-grid">
              {includeItems.map((item) => (
                <div key={item.label} className="include-item">
                  <strong>{item.label}</strong>
                  <p>{item.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Project Gallery: The Most Important Section */}
        <section className="section">
          <div className="container">
            <div className="section-heading">
              <span className="eyebrow">Project gallery</span>
              <h2>Your Project Gallery Is Your Strongest Sales Tool</h2>
              <p className="section-sub">
                Clients comparing general contractors for a major renovation or a commercial
                project want to see proof of range and quality before they ever pick up the
                phone.
              </p>
            </div>
            <div className="benefits-grid">
              {galleryFeatures.map((f, i) => (
                <div key={f.title} className="benefit-card">
                  <span className="benefit-num">0{i + 1}</span>
                  <h3>{f.title}</h3>
                  <p>{f.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Local SEO Structure for General Contractors */}
        <section className="section section-tinted">
          <div className="container">
            <div className="section-heading">
              <span className="eyebrow">Local visibility</span>
              <h2>Local SEO Structure for General Contractors</h2>
              <p className="section-sub">
                Every general contractor website we build starts with a local SEO structure so
                your service area is clear to both visitors and search engines. No agency can
                guarantee a specific ranking — what we can do is build the technical foundation
                that supports your visibility over time.
              </p>
            </div>
            <div className="includes-grid">
              {localSeoItems.map((item) => (
                <div key={item.label} className="include-item">
                  <strong>{item.label}</strong>
                  <p>{item.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Pricing */}
        <section className="section">
          <div className="container">
            <div className="section-heading">
              <span className="eyebrow">Pricing</span>
              <h2>General Contractor Website Pricing</h2>
              <p className="section-sub">
                Simple, one-time pricing to launch your website, plus an optional monthly plan
                to keep it maintained and locally visible.
              </p>
            </div>
            <div className="pricing-cards pricing-cards--three">
              <div className="pricing-card">
                <p className="pricing-label">Starter Website</p>
                <p className="pricing-price">$499 <span>one-time</span></p>
                <p className="pricing-sublabel">A focused one-page website</p>
                <ul>
                  <li>One-page website</li>
                  <li>Mobile-first responsive design</li>
                  <li>Mobile call button</li>
                  <li>Estimate request form</li>
                </ul>
                <Link href="/en/free-website-audit" className="btn btn-secondary">Get Started →</Link>
              </div>
              <div className="pricing-card pricing-card--featured">
                <span className="pricing-badge">Most Popular</span>
                <p className="pricing-label">Growth Website</p>
                <p className="pricing-price">$899 <span>one-time</span></p>
                <p className="pricing-sublabel">A multi-page website with a full project gallery</p>
                <ul>
                  <li>Multiple project-type pages</li>
                  <li>Service area page</li>
                  <li>Full project gallery</li>
                  <li>Licensing and insurance details</li>
                  <li>Local SEO structure included</li>
                </ul>
                <Link href="/en/free-website-audit" className="btn btn-primary">Get Started →</Link>
              </div>
              <div className="pricing-card">
                <p className="pricing-label">Website Care & Local Visibility</p>
                <p className="pricing-price">$79 <span>/month</span></p>
                <p className="pricing-sublabel">Ongoing maintenance and local visibility support</p>
                <ul>
                  <li>Hosting and maintenance</li>
                  <li>Content updates</li>
                  <li>Local visibility support</li>
                  <li>No ranking guarantees</li>
                </ul>
                <Link href="/en/free-website-audit" className="btn btn-secondary">Add This Plan →</Link>
                <p className="page-cta-note">Cancel anytime.</p>
              </div>
            </div>
            <p style={{ textAlign: 'center', marginTop: '1.5rem' }}>
              <Link href="/en/pricing" style={{ color: 'var(--primary)', textDecoration: 'underline', fontSize: '0.9rem' }}>
                See full pricing details →
              </Link>
            </p>
          </div>
        </section>

        {/* FAQ */}
        <section className="section section-tinted">
          <div className="container">
            <div className="section-heading">
              <span className="eyebrow">FAQ</span>
              <h2>Frequently Asked Questions</h2>
            </div>
            <div className="faq-accordion">
              {faqs.map(({ q, a }, i) => (
                <details key={i} className="faq-item">
                  <summary className="faq-question">
                    <span>{q}</span>
                    <svg className="faq-chevron" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                      <path d="M5 7l5 5 5-5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                  </summary>
                  <div className="faq-answer">
                    <p>{a}</p>
                  </div>
                </details>
              ))}
            </div>
          </div>
        </section>

        {/* Final CTA */}
        <section className="section">
          <div className="container">
            <div className="page-cta-block">
              <h2>Request a Free General Contractor Website Audit</h2>
              <p>
                Send us your current website, or tell us about your company if you
                don&apos;t have one yet. We&apos;ll give you honest, no-obligation feedback on
                what would help you present your project range and win more estimates.
              </p>
              <Link href="/en/free-website-audit" className="btn btn-primary btn-lg">
                Request My Free Audit
                <svg className="btn-icon" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                  <path d="M4 10h12M11 5l5 5-5 5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </Link>
            </div>
          </div>
        </section>

      </main>
      <Footer locale="en" />
    </>
  );
}
