import { MetadataRoute } from 'next';

/**
 * Date de dernière modification réelle de chaque page, dérivée de
 * `git log -1 --format=%aI -- <fichier>` au moment de la correction #185.
 * À mettre à jour manuellement quand une PR modifie le contenu visible
 * d'une page — `new Date()` évalué au build envoie un signal de fraîcheur
 * bruyant que Google ignore (toutes les URLs changent à chaque déploiement).
 */
const LAST_MOD: Record<string, string> = {
  '/': '2026-08-12',
  '/offres': '2026-08-10',
  '/tarifs': '2026-08-12',
  '/creation-site-internet-artisan': '2026-08-12',
  '/creation-site-internet-tpe-pme': '2026-08-12',
  '/refonte-site-internet': '2026-08-12',
  '/maintenance-site-web': '2026-08-12',
  '/seo-local': '2026-08-12',
  '/a-propos': '2026-08-12',
  '/faq': '2026-08-12',
  '/comment-ca-marche': '2026-08-12',
  '/avis': '2026-07-28',
  '/realisations': '2026-08-12',
  '/realisations/escalee-gouts': '2026-08-12',
  '/realisations/lenora-conciergerie': '2026-08-12',
  '/realisations/content-by-denise': '2026-08-12',
  '/realisations/qit-concierge': '2026-08-12',
  '/creation': '2026-07-20',
  '/refonte': '2026-07-20',
  '/politique-confidentialite': '2026-08-12',
  '/mentions-legales': '2026-08-12',
  '/cgu': '2026-07-28',
  '/cgv': '2026-07-28',
  '/agence-web-drome': '2026-07-28',
  '/agence-web-ardeche': '2026-07-28',
  '/agence-web-isere': '2026-07-28',
  '/agence-web-rhone': '2026-07-28',
  '/agence-web-ain': '2026-07-28',
  '/agence-web-loire': '2026-07-28',
  '/agence-web-savoie': '2026-07-28',
  '/agence-web-haute-savoie': '2026-07-28',
  '/parrainage': '2026-08-12',
  '/en': '2026-08-12',
  '/en/parrainage': '2026-08-13',
  '/en/free-website-audit': '2026-08-12',
  '/en/pricing': '2026-08-12',
  '/en/offers': '2026-08-12',
  '/en/website-creation-tradespeople': '2026-08-12',
  '/en/website-creation-small-business': '2026-08-12',
  '/en/website-redesign': '2026-08-12',
  '/en/roofing-websites': '2026-08-12',
  '/en/landscaping-websites': '2026-08-12',
  '/en/painting-contractor-websites': '2026-08-12',
  '/en/general-contractor-websites': '2026-08-12',
  '/en/remodeling-contractor-websites': '2026-08-12',
  '/en/gutter-company-websites': '2026-08-12',
  '/en/hvac-websites': '2026-08-12',
  '/en/resources': '2026-08-12',
  '/en/resources/contractor-website-guide': '2026-08-12',
  '/en/resources/contractor-website-cost': '2026-08-12',
  '/en/resources/contractor-website-examples': '2026-08-12',
  '/en/case-studies': '2026-08-12',
  '/en/contractor-websites': '2026-08-12',
  '/en/contractor-websites/georgia': '2026-08-12',
  '/en/contractor-websites/colorado': '2026-08-12',
  '/en/contractor-websites/texas': '2026-08-12',
  '/en/contractor-websites/florida': '2026-08-12',
  '/en/contractor-websites/north-carolina': '2026-08-12',
  '/en/home-service-websites': '2026-08-12',
  '/en/plumber-websites': '2026-08-12',
  '/en/electrician-websites': '2026-08-12',
  '/en/website-maintenance': '2026-08-12',
  '/en/local-seo': '2026-08-12',
  '/en/how-it-works': '2026-08-12',
  '/en/reviews': '2026-08-12',
  '/en/faq': '2026-08-12',
  '/en/about': '2026-08-12',
  '/en/legal-notice': '2026-08-12',
  '/en/terms-of-use': '2026-07-28',
  '/en/terms-of-sale': '2026-07-28',
  '/en/privacy-policy': '2026-08-12',
  '/en/web-agency-drome': '2026-07-28',
  '/en/web-agency-ardeche': '2026-07-28',
  '/en/web-agency-isere': '2026-07-28',
  '/en/web-agency-rhone': '2026-07-28',
  '/en/web-agency-ain': '2026-07-28',
  '/en/web-agency-loire': '2026-07-28',
  '/en/web-agency-savoie': '2026-07-28',
  '/en/web-agency-haute-savoie': '2026-07-28',
};

interface RouteDef {
  path: string;
  changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency'];
  priority: number;
}

const ROUTES: readonly RouteDef[] = [
  { path: '/', changeFrequency: 'monthly', priority: 1 },
  { path: '/offres', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/tarifs', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/creation-site-internet-artisan', changeFrequency: 'monthly', priority: 0.85 },
  { path: '/creation-site-internet-tpe-pme', changeFrequency: 'monthly', priority: 0.85 },
  { path: '/refonte-site-internet', changeFrequency: 'monthly', priority: 0.85 },
  { path: '/maintenance-site-web', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/seo-local', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/a-propos', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/faq', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/comment-ca-marche', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/avis', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/realisations', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/realisations/escalee-gouts', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/realisations/lenora-conciergerie', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/realisations/content-by-denise', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/realisations/qit-concierge', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/creation', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/refonte', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/politique-confidentialite', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/mentions-legales', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/cgu', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/cgv', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/agence-web-drome', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/agence-web-ardeche', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/agence-web-isere', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/agence-web-rhone', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/agence-web-ain', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/agence-web-loire', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/agence-web-savoie', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/agence-web-haute-savoie', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/parrainage', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/en', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/en/parrainage', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/en/free-website-audit', changeFrequency: 'monthly', priority: 0.85 },
  { path: '/en/pricing', changeFrequency: 'monthly', priority: 0.85 },
  { path: '/en/offers', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/en/website-creation-tradespeople', changeFrequency: 'monthly', priority: 0.85 },
  { path: '/en/website-creation-small-business', changeFrequency: 'monthly', priority: 0.85 },
  { path: '/en/website-redesign', changeFrequency: 'monthly', priority: 0.85 },
  { path: '/en/roofing-websites', changeFrequency: 'monthly', priority: 0.85 },
  { path: '/en/landscaping-websites', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/painting-contractor-websites', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/general-contractor-websites', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/remodeling-contractor-websites', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/gutter-company-websites', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/hvac-websites', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/resources', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/resources/contractor-website-guide', changeFrequency: 'monthly', priority: 0.65 },
  { path: '/en/resources/contractor-website-cost', changeFrequency: 'monthly', priority: 0.65 },
  { path: '/en/resources/contractor-website-examples', changeFrequency: 'monthly', priority: 0.65 },
  { path: '/en/case-studies', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/en/contractor-websites', changeFrequency: 'monthly', priority: 0.85 },
  { path: '/en/contractor-websites/georgia', changeFrequency: 'monthly', priority: 0.6 },
  { path: '/en/contractor-websites/colorado', changeFrequency: 'monthly', priority: 0.6 },
  { path: '/en/contractor-websites/texas', changeFrequency: 'monthly', priority: 0.6 },
  { path: '/en/contractor-websites/florida', changeFrequency: 'monthly', priority: 0.6 },
  { path: '/en/contractor-websites/north-carolina', changeFrequency: 'monthly', priority: 0.6 },
  { path: '/en/home-service-websites', changeFrequency: 'monthly', priority: 0.85 },
  { path: '/en/plumber-websites', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/electrician-websites', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/website-maintenance', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/en/local-seo', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/en/how-it-works', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/en/reviews', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/en/faq', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/en/about', changeFrequency: 'monthly', priority: 0.75 },
  { path: '/en/legal-notice', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/en/terms-of-use', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/en/terms-of-sale', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/en/privacy-policy', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/en/web-agency-drome', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/web-agency-ardeche', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/web-agency-isere', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/web-agency-rhone', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/web-agency-ain', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/web-agency-loire', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/web-agency-savoie', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/en/web-agency-haute-savoie', changeFrequency: 'monthly', priority: 0.7 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  return ROUTES.map(({ path, changeFrequency, priority }) => ({
    url: `https://pixeloria.fr${path === '/' ? '' : path}`,
    lastModified: LAST_MOD[path],
    changeFrequency,
    priority,
  }));
}
