import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: 'https://pixeloria.fr', lastModified: new Date(), changeFrequency: 'monthly', priority: 1 },
    { url: 'https://pixeloria.fr/offres', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://pixeloria.fr/tarifs', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://pixeloria.fr/creation-site-internet-artisan', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: 'https://pixeloria.fr/creation-site-internet-tpe-pme', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: 'https://pixeloria.fr/refonte-site-internet', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: 'https://pixeloria.fr/maintenance-site-web', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/seo-local', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/a-propos', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/faq', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/comment-ca-marche', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/avis', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/realisations', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/realisations/escalee-gouts', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/realisations/lenora-conciergerie', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/realisations/content-by-denise', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/realisations/qit-concierge', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/creation', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/refonte', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/politique-confidentialite', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://pixeloria.fr/mentions-legales', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://pixeloria.fr/cgu', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://pixeloria.fr/cgv', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://pixeloria.fr/agence-web-drome', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-ardeche', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-isere', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-rhone', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-ain', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-loire', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-savoie', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-haute-savoie', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/parrainage', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/en', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://pixeloria.fr/en/parrainage', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/en/pricing', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: 'https://pixeloria.fr/en/offers', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://pixeloria.fr/en/website-creation-tradespeople', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: 'https://pixeloria.fr/en/website-creation-small-business', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: 'https://pixeloria.fr/en/website-redesign', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: 'https://pixeloria.fr/en/website-maintenance', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/en/local-seo', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/en/how-it-works', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/en/reviews', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/en/faq', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/en/about', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/en/legal-notice', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://pixeloria.fr/en/terms-of-use', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://pixeloria.fr/en/terms-of-sale', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://pixeloria.fr/en/privacy-policy', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://pixeloria.fr/en/web-agency-drome', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/web-agency-ardeche', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/web-agency-isere', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/web-agency-rhone', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/web-agency-ain', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/web-agency-loire', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/web-agency-savoie', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/web-agency-haute-savoie', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
  ];
}
