import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: 'https://pixeloria.fr', lastModified: new Date(), changeFrequency: 'monthly', priority: 1 },
    { url: 'https://pixeloria.fr/offres', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://pixeloria.fr/creation-site-internet-artisan', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: 'https://pixeloria.fr/creation-site-internet-tpe-pme', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: 'https://pixeloria.fr/refonte-site-internet', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: 'https://pixeloria.fr/maintenance-site-web', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/seo-local', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/a-propos', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/realisations', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/realisations/escalee-gouts', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/realisations/lenora-conciergerie', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/realisations/content-by-denise', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/realisations/qit-concierge', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/creation', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/refonte', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/exemples/artisan-batiment', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/exemples/entreprise-renovation', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/exemples/conciergerie', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/exemples/agence-immobiliere', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/exemples/commerce-local', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/exemples/independant', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/politique-confidentialite', lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: 'https://pixeloria.fr/agence-web-drome', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-ardeche', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-isere', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-rhone', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-ain', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-loire', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-savoie', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/agence-web-haute-savoie', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/parrainage', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/en', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://pixeloria.fr/en/pricing', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: 'https://pixeloria.fr/en/how-it-works', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/en/reviews', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://pixeloria.fr/en/faq', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/en/about', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.75 },
    { url: 'https://pixeloria.fr/en/testimonial', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: 'https://pixeloria.fr/en/examples/contractors', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/examples/renovation-companies', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/examples/hospitality-concierge', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/examples/real-estate', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/examples/local-shops', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://pixeloria.fr/en/examples/freelancers-consultants', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
  ];
}
